os:
  editPreset: 'nvim'

keybindings:
  universal:
    return: '<c-\>'

gui:
  theme:
    slectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline

git:
  showIcons: true
  paging:
    colorArg: always
    pager: delta --syntax-theme Catppuccin-frappe --paging=never --dark -s 
